---
- name: test book
  hosts: localhost
  become: yes
  tasks:

    - name: Install apt repositories
      apt_repository:
        repo: '{{ item }}'
      with_items:
        - ppa:deadsnakes/ppa

    - name: Install additional apt packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: True
      with_items:
        - git
        - python3.12
        - synaptic
        - build-essential
        - zlib1g-dev
        - libssl-dev 
        - libbz2-dev 
        - libreadline-dev 
        - libsqlite3-dev 
        - curl
        - libncursesw5-dev 
        - xz-utils 
        - tk-dev 
        - libxml2-dev 
        - libxmlsec1-dev 
        - libffi-dev 
        - liblzma-dev
        - gcc
        - gconf2
        - libasound2
        - libnotify4
        - libnspr4
        - gdebi-core
        - ubuntu-desktop
        - xclip

    # - name: Install additional snap packages
    #   snap:
    #     name:
    #       - discord
